import ChartPie from './pie.vue'
import ChartBar from './bar.vue'
import ChartBar2 from './bar2.vue'
import ChartLine from './line.vue'
import ChartLine2 from './line2.vue'
import ChartLine3 from './line3.vue'
import ChartLine5 from './line5.vue'
import ChartTree from './tree.vue'
import ChartMap from './map.vue'
export { ChartPie, ChartBar, ChartBar2, ChartLine, ChartLine2, ChartLine3,ChartLine5, ChartTree, ChartMap }
